In [33]:
import pymongo
from pymongo import MongoClient

In [2]:
import json

In [34]:
import pandas as pd

In [71]:
client = pymongo.MongoClient("mongodb+srv://username:password@cluster0.bdgfv.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.students
records = db.assignment

In [37]:
data=pd.read_json("students.json", lines=True)
data

,_id,name,scores
0,0,aimee Zank,"[{'score': 1.463179736705023, 'type': 'exam'},..."
1,1,Aurelia Menendez,"[{'score': 60.06045071030959, 'type': 'exam'},..."
2,2,Corliss Zuk,"[{'score': 67.03077096065002, 'type': 'exam'},..."
3,3,Bao Ziglar,"[{'score': 71.64343899778332, 'type': 'exam'},..."
4,4,Zachary Langlais,"[{'score': 78.68385091304332, 'type': 'exam'},..."
5,5,Wilburn Spiess,"[{'score': 44.87186330181261, 'type': 'exam'},..."
6,6,Jenette Flanders,"[{'score': 37.32285459166097, 'type': 'exam'},..."
7,7,Salena Olmos,"[{'score': 90.37826509157176, 'type': 'exam'},..."
8,8,Daphne Zheng,"[{'score': 22.13583712862635, 'type': 'exam'},..."
9,9,Sanda Ryba,"[{'score': 97.00509953654694, 'type': 'exam'},..."
10,10,Denisha Cast,"[{'score': 45.61876862259409, 'type': 'exam'},..."
11,11,Marcus Blohm,"[{'score': 78.42617835651868, 'type': 'exam'},..."
12,12,Quincy Danaher,"[{'score': 54.29841278520669, 'type': 'exam'},..."
13,13,Jessika Dagenais,"[{'score': 90.47179954427436, 'type': 'exam'},..."
14,14,Alix Sherrill,"[{'score': 25.15924151998215, 'type': 'exam'},..."
15,15,Tambra Mercure,"[{'score': 69.1565022533158, 'type': 'exam'}, ..."
16,16,Dodie Staller,"[{'score': 7.772386442858281, 'type': 'exam'},..."
17,17,Fletcher Mcconnell,"[{'score': 39.41011069729274, 'type': 'exam'},..."
18,18,Verdell Sowinski,"[{'score': 62.12870233109035, 'type': 'exam'},..."
19,19,Gisela Levin,"[{'score': 44.51211101958831, 'type': 'exam'},..."
20,20,Tressa Schwing,"[{'score': 42.17439799514388, 'type': 'exam'},..."
21,21,Rosana Vales,"[{'score': 46.2289476258328, 'type': 'exam'}, ..."
22,22,Margart Vitello,"[{'score': 75.04996547553947, 'type': 'exam'},..."
23,23,Tamika Schildgen,"[{'score': 45.65432764125526, 'type': 'exam'},..."
24,24,Jesusa Rickenbacker,"[{'score': 86.0319702155683, 'type': 'exam'}, ..."
25,25,Rudolph Domingo,"[{'score': 74.75289335591543, 'type': 'exam'},..."
26,26,Jonie Raby,"[{'score': 19.17861192576963, 'type': 'exam'},..."
27,27,Edgar Sarkis,"[{'score': 8.606983261043888, 'type': 'exam'},..."
28,28,Laureen Salomone,"[{'score': 3.677565278992456, 'type': 'exam'},..."
29,29,Gwyneth Garling,"[{'score': 48.36644963899371, 'type': 'exam'},..."
...,...,...,...
170,170,Danika Loeffler,"[{'score': 80.13802901122058, 'type': 'exam'},..."
171,171,Chad Rahe,"[{'score': 81.24054522370292, 'type': 'exam'},..."
172,172,Joaquina Arbuckle,"[{'score': 35.43562368815135, 'type': 'exam'},..."
173,173,Vinnie Auerbach,"[{'score': 57.26312067710243, 'type': 'exam'},..."
174,174,Dusti Lemmond,"[{'score': 91.51968055194875, 'type': 'exam'},..."
175,175,Grady Zemke,"[{'score': 10.37320113489379, 'type': 'exam'},..."
176,176,Vina Matsunaga,"[{'score': 73.30054989074031, 'type': 'exam'},..."
177,177,Rubie Winton,"[{'score': 36.1767454709986, 'type': 'exam'}, ..."
178,178,Whitley Fears,"[{'score': 20.84454374176408, 'type': 'exam'},..."
179,179,Gena Riccio,"[{'score': 81.49070346172086, 'type': 'exam'},..."
180,180,Kim Xu,"[{'score': 29.1596029917098, 'type': 'exam'}, ..."
181,181,Merissa Mann,"[{'score': 0.730027971743296, 'type': 'exam'},..."
182,182,Jenise Mcguffie,"[{'score': 83.68438201130127, 'type': 'exam'},..."
183,183,Cody Strouth,"[{'score': 32.99854612126559, 'type': 'exam'},..."
184,184,Harriett Velarde,"[{'score': 41.47988283148075, 'type': 'exam'},..."
185,185,Kam Senters,"[{'score': 49.8822537074033, 'type': 'exam'}, ..."
186,186,Leonida Lafond,"[{'score': 8.125073097960179, 'type': 'exam'},..."
187,187,Devorah Smartt,"[{'score': 23.94616611315642, 'type': 'exam'},..."
188,188,Leola Lundin,"[{'score': 60.314725741828, 'type': 'exam'}, {..."
189,189,Tonia Surace,"[{'score': 67.93405589675187, 'type': 'exam'},..."
190,190,Adrien Renda,"[{'score': 64.16109192679477, 'type': 'exam'},..."
191,191,Efrain Claw,"[{'score': 94.67153825229884, 'type': 'exam'},..."
192,192,Len Treiber,"[{'score': 39.19832917406515, 'type': 'exam'},..."
193,193,Mariela Sherer,"[{'score': 47.67196715489599, 'type': 'exam'},..."
194,194,Echo Pippins,"[{'score': 18.09013691507853, 'type': 'exam'},..."
195,195,Linnie Weigel,"[{'score': 52.44578368517977, 'type': 'exam'},..."
196,196,Santiago Dollins,"[{'score': 52.04052571137036, 'type': 'exam'},..."
197,197,Tonisha Games,"[{'score': 38.51269589995049, 'type': 'exam'},..."
198,198,Timothy Harrod,"[{'score': 11.9075674046519, 'type': 'exam'}, ..."
199,199,Rae Kohout,"[{'score': 82.11742562118049, 'type': 'exam'},..."

In [38]:
print(data['scores'][0][0])
print(data['scores'][0][1])
print(data['scores'][0][2])

{'score': 1.463179736705023, 'type': 'exam'}
{'score': 11.78273309957772, 'type': 'quiz'}
{'score': 35.8740349954354, 'type': 'homework'}

In [15]:
print(data['scores'][0][0]['score'])
print(data['scores'][0][1]['score'])
print(data['scores'][0][2]['score'])

1.463179736705023
11.78273309957772
35.8740349954354

In [13]:
print(len(data['scores'][0]))

3

In [39]:
exam = []
quiz = []
homework = []

for i in range(len(data['scores'])):
    exam.append(data['scores'][i][0]['score'])
    quiz.append(data['scores'][i][1]['score'])
    homework.append(data['scores'][i][2]['score'])
    
#print(exam)
#print(quiz)
#print(homework)

In [40]:
data['Exam']=exam
data['Quiz']=quiz
data['HomeWork']=homework
data

,_id,name,scores,Exam,Quiz,HomeWork
0,0,aimee Zank,"[{'score': 1.463179736705023, 'type': 'exam'},...",1.463180,11.782733,35.874035
1,1,Aurelia Menendez,"[{'score': 60.06045071030959, 'type': 'exam'},...",60.060451,52.797907,71.761334
2,2,Corliss Zuk,"[{'score': 67.03077096065002, 'type': 'exam'},...",67.030771,6.301852,66.283447
3,3,Bao Ziglar,"[{'score': 71.64343899778332, 'type': 'exam'},...",71.643439,24.802213,42.261471
4,4,Zachary Langlais,"[{'score': 78.68385091304332, 'type': 'exam'},...",78.683851,90.296310,34.416201
5,5,Wilburn Spiess,"[{'score': 44.87186330181261, 'type': 'exam'},...",44.871863,25.723951,63.422883
6,6,Jenette Flanders,"[{'score': 37.32285459166097, 'type': 'exam'},...",37.322855,28.326350,81.571153
7,7,Salena Olmos,"[{'score': 90.37826509157176, 'type': 'exam'},...",90.378265,42.487807,96.529862
8,8,Daphne Zheng,"[{'score': 22.13583712862635, 'type': 'exam'},...",22.135837,14.639699,75.941237
9,9,Sanda Ryba,"[{'score': 97.00509953654694, 'type': 'exam'},...",97.005100,97.804496,25.273685
10,10,Denisha Cast,"[{'score': 45.61876862259409, 'type': 'exam'},...",45.618769,98.357232,55.908357
11,11,Marcus Blohm,"[{'score': 78.42617835651868, 'type': 'exam'},...",78.426178,82.583728,87.499247
12,12,Quincy Danaher,"[{'score': 54.29841278520669, 'type': 'exam'},...",54.298413,85.612702,80.407324
13,13,Jessika Dagenais,"[{'score': 90.47179954427436, 'type': 'exam'},...",90.471800,90.300140,95.177538
14,14,Alix Sherrill,"[{'score': 25.15924151998215, 'type': 'exam'},...",25.159242,68.644840,24.684622
15,15,Tambra Mercure,"[{'score': 69.1565022533158, 'type': 'exam'}, ...",69.156502,3.311794,45.031790
16,16,Dodie Staller,"[{'score': 7.772386442858281, 'type': 'exam'},...",7.772386,31.843002,80.521364
17,17,Fletcher Mcconnell,"[{'score': 39.41011069729274, 'type': 'exam'},...",39.410111,81.132703,97.701166
18,18,Verdell Sowinski,"[{'score': 62.12870233109035, 'type': 'exam'},...",62.128702,84.745862,81.589478
19,19,Gisela Levin,"[{'score': 44.51211101958831, 'type': 'exam'},...",44.512111,0.657850,93.363417
20,20,Tressa Schwing,"[{'score': 42.17439799514388, 'type': 'exam'},...",42.174398,71.993148,81.239726
21,21,Rosana Vales,"[{'score': 46.2289476258328, 'type': 'exam'}, ...",46.228948,98.341642,36.187697
22,22,Margart Vitello,"[{'score': 75.04996547553947, 'type': 'exam'},...",75.049965,10.230465,96.725205
23,23,Tamika Schildgen,"[{'score': 45.65432764125526, 'type': 'exam'},...",45.654328,64.329270,83.539334
24,24,Jesusa Rickenbacker,"[{'score': 86.0319702155683, 'type': 'exam'}, ...",86.031970,1.967495,61.108611
25,25,Rudolph Domingo,"[{'score': 74.75289335591543, 'type': 'exam'},...",74.752893,38.541365,35.255434
26,26,Jonie Raby,"[{'score': 19.17861192576963, 'type': 'exam'},...",19.178612,76.389036,44.396057
27,27,Edgar Sarkis,"[{'score': 8.606983261043888, 'type': 'exam'},...",8.606983,58.711805,15.337262
28,28,Laureen Salomone,"[{'score': 3.677565278992456, 'type': 'exam'},...",3.677565,7.119463,82.873089
29,29,Gwyneth Garling,"[{'score': 48.36644963899371, 'type': 'exam'},...",48.366450,10.378270,93.266393
...,...,...,...,...,...,...
170,170,Danika Loeffler,"[{'score': 80.13802901122058, 'type': 'exam'},...",80.138029,9.613196,88.158011
171,171,Chad Rahe,"[{'score': 81.24054522370292, 'type': 'exam'},...",81.240545,17.449292,82.778700
172,172,Joaquina Arbuckle,"[{'score': 35.43562368815135, 'type': 'exam'},...",35.435624,89.746410,99.138687
173,173,Vinnie Auerbach,"[{'score': 57.26312067710243, 'type': 'exam'},...",57.263121,20.635830,77.026385
174,174,Dusti Lemmond,"[{'score': 91.51968055194875, 'type': 'exam'},...",91.519681,50.376827,51.539391
175,175,Grady Zemke,"[{'score': 10.37320113489379, 'type': 'exam'},...",10.373201,10.513444,85.471800
176,176,Vina Matsunaga,"[{'score': 73.30054989074031, 'type': 'exam'},...",73.300550,4.217546,56.311509
177,177,Rubie Winton,"[{'score': 36.1767454709986, 'type': 'exam'}, ...",36.176745,89.397381,90.833262
178,178,Whitley Fears,"[{'score': 20.84454374176408, 'type': 'exam'},...",20.844544,57.148513,99.772377
179,179,Gena Riccio,"[{'score': 81.49070346172086, 'type': 'exam'},...",81.490703,23.126534,96.545910
180,180,Kim Xu,"[{'score': 29.1596029917098, 'type': 'exam'}, ...",29.159603,74.418363,56.649655
181,181,Merissa Mann,"[{'score': 0.730027971743296, 'type': 'exam'},...",0.730028,39.491706,60.496193
182,182,Jenise Mcguffie,"[{'score': 83.68438201130127, 'type': 'exam'},...",83.684382,73.799318,89.572009
183,183,Cody Strouth,"[{'score': 32.99854612126559, 'type': 'exam'},...",32.998546,78.617203,89.628476
184,184,Harriett Velarde,"[{'score': 41.47988283148075, 'type': 'exam'},...",41.479883,95.694937,83.039160
185,185,Kam Senters,"[{'score': 49.8822537074033, 'type': 'exam'}, ...",49.882254,45.295154,68.880490
186,186,Leonida Lafond,"[{'score': 8.125073097960179, 'type': 'exam'},...",8.125073,0.201789,90.130819
187,187,Devorah Smartt,"[{'score': 23.94616611315642, 'type': 'exam'},...",23.946166,13.273711,63.172811
188,188,Leola Lundin,"[{'score': 60.314725741828, 'type': 'exam'}, {...",60.314726,41.123275,74.869918
189,189,Tonia Surace,"[{'score': 67.93405589675187, 'type': 'exam'},...",67.934056,31.497211,82.364959
190,190,Adrien Renda,"[{'score': 64.16109192679477, 'type': 'exam'},...",64.161092,66.937306,96.056034
191,191,Efrain Claw,"[{'score': 94.67153825229884, 'type': 'exam'},...",94.671538,82.300879,75.860758
192,192,Len Treiber,"[{'score': 39.19832917406515, 'type': 'exam'},...",39.198329,98.716793,44.822893
193,193,Mariela Sherer,"[{'score': 47.67196715489599, 'type': 'exam'},...",47.671967,41.557435,70.461281
194,194,Echo Pippins,"[{'score': 18.09013691507853, 'type': 'exam'},...",18.090137,35.003070,80.179652
195,195,Linnie Weigel,"[{'score': 52.44578368517977, 'type': 'exam'},...",52.445784,90.777505,11.750084
196,196,Santiago Dollins,"[{'score': 52.04052571137036, 'type': 'exam'},...",52.040526,33.633001,78.792574
197,197,Tonisha Games,"[{'score': 38.51269589995049, 'type': 'exam'},...",38.512696,31.162876,79.158564
198,198,Timothy Harrod,"[{'score': 11.9075674046519, 'type': 'exam'}, ...",11.907567,20.518800,64.856504
199,199,Rae Kohout,"[{'score': 82.11742562118049, 'type': 'exam'},...",82.117426,49.612955,28.868237

In [72]:

for i in range(len(data)):
    deltail=data.iloc[i].to_dict()
    records.insert_one(deltail)

In [28]:
x=records.find_one()
print(x)

None

In [41]:
data.drop(['scores'],axis=1,inplace=True)
data.drop(['_id'],axis=1,inplace=True)

In [42]:
data

                    name       Exam       Quiz   HomeWork
0             aimee Zank   1.463180  11.782733  35.874035
1       Aurelia Menendez  60.060451  52.797907  71.761334
2            Corliss Zuk  67.030771   6.301852  66.283447
3             Bao Ziglar  71.643439  24.802213  42.261471
4       Zachary Langlais  78.683851  90.296310  34.416201
5         Wilburn Spiess  44.871863  25.723951  63.422883
6       Jenette Flanders  37.322855  28.326350  81.571153
7           Salena Olmos  90.378265  42.487807  96.529862
8           Daphne Zheng  22.135837  14.639699  75.941237
9             Sanda Ryba  97.005100  97.804496  25.273685
10          Denisha Cast  45.618769  98.357232  55.908357
11          Marcus Blohm  78.426178  82.583728  87.499247
12        Quincy Danaher  54.298413  85.612702  80.407324
13      Jessika Dagenais  90.471800  90.300140  95.177538
14         Alix Sherrill  25.159242  68.644840  24.684622
15        Tambra Mercure  69.156502   3.311794  45.031790
16         Dodie Staller   7.772386  31.843002  80.521364
17    Fletcher Mcconnell  39.410111  81.132703  97.701166
18      Verdell Sowinski  62.128702  84.745862  81.589478
19          Gisela Levin  44.512111   0.657850  93.363417
20        Tressa Schwing  42.174398  71.993148  81.239726
21          Rosana Vales  46.228948  98.341642  36.187697
22       Margart Vitello  75.049965  10.230465  96.725205
23      Tamika Schildgen  45.654328  64.329270  83.539334
24   Jesusa Rickenbacker  86.031970   1.967495  61.108611
25       Rudolph Domingo  74.752893  38.541365  35.255434
26            Jonie Raby  19.178612  76.389036  44.396057
27          Edgar Sarkis   8.606983  58.711805  15.337262
28      Laureen Salomone   3.677565   7.119463  82.873089
29       Gwyneth Garling  48.366450  10.378270  93.266393
..                   ...        ...        ...        ...
170      Danika Loeffler  80.138029   9.613196  88.158011
171            Chad Rahe  81.240545  17.449292  82.778700
172    Joaquina Arbuckle  35.435624  89.746410  99.138687
173      Vinnie Auerbach  57.263121  20.635830  77.026385
174        Dusti Lemmond  91.519681  50.376827  51.539391
175          Grady Zemke  10.373201  10.513444  85.471800
176       Vina Matsunaga  73.300550   4.217546  56.311509
177         Rubie Winton  36.176745  89.397381  90.833262
178        Whitley Fears  20.844544  57.148513  99.772377
179          Gena Riccio  81.490703  23.126534  96.545910
180               Kim Xu  29.159603  74.418363  56.649655
181         Merissa Mann   0.730028  39.491706  60.496193
182      Jenise Mcguffie  83.684382  73.799318  89.572009
183         Cody Strouth  32.998546  78.617203  89.628476
184     Harriett Velarde  41.479883  95.694937  83.039160
185          Kam Senters  49.882254  45.295154  68.880490
186       Leonida Lafond   8.125073   0.201789  90.130819
187       Devorah Smartt  23.946166  13.273711  63.172811
188         Leola Lundin  60.314726  41.123275  74.869918
189         Tonia Surace  67.934056  31.497211  82.364959
190         Adrien Renda  64.161092  66.937306  96.056034
191          Efrain Claw  94.671538  82.300879  75.860758
192          Len Treiber  39.198329  98.716793  44.822893
193       Mariela Sherer  47.671967  41.557435  70.461281
194         Echo Pippins  18.090137  35.003070  80.179652
195        Linnie Weigel  52.445784  90.777505  11.750084
196     Santiago Dollins  52.040526  33.633001  78.792574
197        Tonisha Games  38.512696  31.162876  79.158564
198       Timothy Harrod  11.907567  20.518800  64.856504
199           Rae Kohout  82.117426  49.612955  28.868237

[200 rows x 4 columns]

In [69]:
#using loc
#data['Total']=data.loc[:,['Exam','Quiz','HomeWork']].sum(axis=1)

#using iloc
data['Total']=data.iloc[:,1 : 4].sum(axis=1)

#using loc
data['Percentage'] = data.loc[:,['Exam','Quiz','HomeWork']].mean(axis= 1)

In [101]:
data

,name,Exam,Quiz,HomeWork,Total,Percentage
0,aimee Zank,1.463180,11.782733,35.874035,49.119948,16.373316
1,Aurelia Menendez,60.060451,52.797907,71.761334,184.619692,61.539897
2,Corliss Zuk,67.030771,6.301852,66.283447,139.616069,46.538690
3,Bao Ziglar,71.643439,24.802213,42.261471,138.707123,46.235708
4,Zachary Langlais,78.683851,90.296310,34.416201,203.396363,67.798788
5,Wilburn Spiess,44.871863,25.723951,63.422883,134.018698,44.672899
6,Jenette Flanders,37.322855,28.326350,81.571153,147.220358,49.073453
7,Salena Olmos,90.378265,42.487807,96.529862,229.395933,76.465311
8,Daphne Zheng,22.135837,14.639699,75.941237,112.716773,37.572258
9,Sanda Ryba,97.005100,97.804496,25.273685,220.083281,73.361094
10,Denisha Cast,45.618769,98.357232,55.908357,199.884357,66.628119
11,Marcus Blohm,78.426178,82.583728,87.499247,248.509154,82.836385
12,Quincy Danaher,54.298413,85.612702,80.407324,220.318438,73.439479
13,Jessika Dagenais,90.471800,90.300140,95.177538,275.949478,91.983159
14,Alix Sherrill,25.159242,68.644840,24.684622,118.488704,39.496235
15,Tambra Mercure,69.156502,3.311794,45.031790,117.500086,39.166695
16,Dodie Staller,7.772386,31.843002,80.521364,120.136753,40.045584
17,Fletcher Mcconnell,39.410111,81.132703,97.701166,218.243980,72.747993
18,Verdell Sowinski,62.128702,84.745862,81.589478,228.464043,76.154681
19,Gisela Levin,44.512111,0.657850,93.363417,138.533377,46.177792
20,Tressa Schwing,42.174398,71.993148,81.239726,195.407273,65.135758
21,Rosana Vales,46.228948,98.341642,36.187697,180.758287,60.252762
22,Margart Vitello,75.049965,10.230465,96.725205,182.005635,60.668545
23,Tamika Schildgen,45.654328,64.329270,83.539334,193.522932,64.507644
24,Jesusa Rickenbacker,86.031970,1.967495,61.108611,149.108076,49.702692
25,Rudolph Domingo,74.752893,38.541365,35.255434,148.549692,49.516564
26,Jonie Raby,19.178612,76.389036,44.396057,139.963705,46.654568
27,Edgar Sarkis,8.606983,58.711805,15.337262,82.656050,27.552017
28,Laureen Salomone,3.677565,7.119463,82.873089,93.670117,31.223372
29,Gwyneth Garling,48.366450,10.378270,93.266393,152.011113,50.670371
...,...,...,...,...,...,...
170,Danika Loeffler,80.138029,9.613196,88.158011,177.909236,59.303079
171,Chad Rahe,81.240545,17.449292,82.778700,181.468537,60.489512
172,Joaquina Arbuckle,35.435624,89.746410,99.138687,224.320720,74.773573
173,Vinnie Auerbach,57.263121,20.635830,77.026385,154.925336,51.641779
174,Dusti Lemmond,91.519681,50.376827,51.539391,193.435898,64.478633
175,Grady Zemke,10.373201,10.513444,85.471800,106.358446,35.452815
176,Vina Matsunaga,73.300550,4.217546,56.311509,133.829604,44.609868
177,Rubie Winton,36.176745,89.397381,90.833262,216.407389,72.135796
178,Whitley Fears,20.844544,57.148513,99.772377,177.765434,59.255145
179,Gena Riccio,81.490703,23.126534,96.545910,201.163147,67.054382
180,Kim Xu,29.159603,74.418363,56.649655,160.227621,53.409207
181,Merissa Mann,0.730028,39.491706,60.496193,100.717927,33.572642
182,Jenise Mcguffie,83.684382,73.799318,89.572009,247.055709,82.351903
183,Cody Strouth,32.998546,78.617203,89.628476,201.244225,67.081408
184,Harriett Velarde,41.479883,95.694937,83.039160,220.213980,73.404660
185,Kam Senters,49.882254,45.295154,68.880490,164.057897,54.685966
186,Leonida Lafond,8.125073,0.201789,90.130819,98.457681,32.819227
187,Devorah Smartt,23.946166,13.273711,63.172811,100.392688,33.464229
188,Leola Lundin,60.314726,41.123275,74.869918,176.307918,58.769306
189,Tonia Surace,67.934056,31.497211,82.364959,181.796226,60.598742
190,Adrien Renda,64.161092,66.937306,96.056034,227.154432,75.718144
191,Efrain Claw,94.671538,82.300879,75.860758,252.833176,84.277725
192,Len Treiber,39.198329,98.716793,44.822893,182.738015,60.912672
193,Mariela Sherer,47.671967,41.557435,70.461281,159.690683,53.230228
194,Echo Pippins,18.090137,35.003070,80.179652,133.272858,44.424286
195,Linnie Weigel,52.445784,90.777505,11.750084,154.973373,51.657791
196,Santiago Dollins,52.040526,33.633001,78.792574,164.466100,54.822033
197,Tonisha Games,38.512696,31.162876,79.158564,148.834135,49.611378
198,Timothy Harrod,11.907567,20.518800,64.856504,97.282871,32.427624
199,Rae Kohout,82.117426,49.612955,28.868237,160.598617,53.532872

Find the student name who scored maximum scores in all (exam, quiz and homework)?

In [91]:
x = db.assignment.find().sort("Total",-1).limit(1)

for i in x:
    print(i['name'])

Jessika Dagenais

 Find students who scored below average in the exam and pass mark is 40%?

In [100]:

for i in records.find({'Exam':{"$lte":40}}).sort('Exam',-1):
    print(i['name'])

Fletcher Mcconnell
Len Treiber
Kurtis Jiles
Tonisha Games
Ty Barbieri
Jenette Flanders
Bao Ziglar
Rubie Winton
Gwen Honig
Joaquina Arbuckle
Barbera Lippman
Richelle Siemers
Harriett Velarde
Santiago Dollins
Malisa Jeanes
Rudolph Domingo
Cody Strouth
Leola Lundin
Ta Sikorski
Kim Xu
Tonisha Games
Joaquina Arbuckle
Aleida Elsass
Echo Pippins
Lucinda Vanderburg
Synthia Labelle
Alix Sherrill
Fletcher Mcconnell
Tandra Meadows
Devorah Smartt
Elizabet Kleine
Daphne Zheng
Jenette Flanders
Tania Hulett
Joel Rueter
Danika Loeffler
Len Treiber
Toshiko Sabella
Kaila Deibler
Whitley Fears
Verdell Sowinski
Kim Xu
Alica Pasley
Jonie Raby
Tandra Meadows
Echo Pippins
Dusti Lemmond
Lady Lefevers
aimee Zank
Kaila Deibler
Gisela Levin
Rosana Vales
Jesusa Rickenbacker
Ernestine Macfarland
Timothy Harrod
Synthia Labelle
Sanda Ryba
Grady Zemke
Barbera Lippman
Ernestine Macfarland
Dinah Sauve
Edgar Sarkis
Omar Bowdoin
Leonida Lafond
Dodie Staller
Jonie Raby
Rubie Winton
Carli Belvins
Darby Wass
Sadie Jernigan
Aurelia Menendez
Cody Strouth
Tamika Schildgen
Laureen Salomone
Karry Petrarca
Denisha Cast
Brain Lachapelle
aimee Zank
Salena Olmos
Merissa Mann
Mariette Batdorf

In [105]:
x = records.aggregate( [
   { "$count": "myCount" }
])
for i in x:
    print(i)

{'myCount': 200}

 Find students who scored below pass mark and assigned them as fail, and above pass mark as pass in all the categories.

In [116]:
x = records.aggregate(
[{
    "$project" :
    {
        "name":1,
        "_id" : 0,
        "result":{
            "$cond":
                    {"if": {"$and" : [{"$gte" : ["$Exam", 40]}, {"$gte" : ["$Quiz", 40]}, {"$gte" : ["$HomeWork", 40]}]},
                    "then" :"pass",
                    "else":"fail"
                 }
                }
    }
}])
for i in x:
    print(i)

{'name': 'aimee Zank', 'result': 'fail'}
{'name': 'Aurelia Menendez', 'result': 'pass'}
{'name': 'Corliss Zuk', 'result': 'fail'}
{'name': 'Bao Ziglar', 'result': 'fail'}
{'name': 'Zachary Langlais', 'result': 'fail'}
{'name': 'Wilburn Spiess', 'result': 'fail'}
{'name': 'Jenette Flanders', 'result': 'fail'}
{'name': 'Salena Olmos', 'result': 'pass'}
{'name': 'Daphne Zheng', 'result': 'fail'}
{'name': 'Sanda Ryba', 'result': 'fail'}
{'name': 'Denisha Cast', 'result': 'pass'}
{'name': 'Marcus Blohm', 'result': 'pass'}
{'name': 'Quincy Danaher', 'result': 'pass'}
{'name': 'Jessika Dagenais', 'result': 'pass'}
{'name': 'Alix Sherrill', 'result': 'fail'}
{'name': 'Tambra Mercure', 'result': 'fail'}
{'name': 'Dodie Staller', 'result': 'fail'}
{'name': 'Fletcher Mcconnell', 'result': 'fail'}
{'name': 'Verdell Sowinski', 'result': 'pass'}
{'name': 'Gisela Levin', 'result': 'fail'}
{'name': 'Tressa Schwing', 'result': 'pass'}
{'name': 'Rosana Vales', 'result': 'fail'}
{'name': 'Margart Vitello', 'result': 'fail'}
{'name': 'Tamika Schildgen', 'result': 'pass'}
{'name': 'Jesusa Rickenbacker', 'result': 'fail'}
{'name': 'Rudolph Domingo', 'result': 'fail'}
{'name': 'Jonie Raby', 'result': 'fail'}
{'name': 'Edgar Sarkis', 'result': 'fail'}
{'name': 'Laureen Salomone', 'result': 'fail'}
{'name': 'Gwyneth Garling', 'result': 'fail'}
{'name': 'Kaila Deibler', 'result': 'fail'}
{'name': 'Tandra Meadows', 'result': 'fail'}
{'name': 'Gwen Honig', 'result': 'pass'}
{'name': 'Sadie Jernigan', 'result': 'fail'}
{'name': 'Carli Belvins', 'result': 'fail'}
{'name': 'Synthia Labelle', 'result': 'fail'}
{'name': 'Eugene Magdaleno', 'result': 'pass'}
{'name': 'Meagan Oakes', 'result': 'fail'}
{'name': 'Richelle Siemers', 'result': 'fail'}
{'name': 'Mariette Batdorf', 'result': 'fail'}
{'name': 'Rachell Aman', 'result': 'fail'}
{'name': 'Aleida Elsass', 'result': 'fail'}
{'name': 'Kayce Kenyon', 'result': 'fail'}
{'name': 'Ernestine Macfarland', 'result': 'fail'}
{'name': 'Houston Valenti', 'result': 'fail'}
{'name': 'Terica Brugger', 'result': 'fail'}
{'name': 'Lady Lefevers', 'result': 'fail'}
{'name': 'Kurtis Jiles', 'result': 'fail'}
{'name': 'Barbera Lippman', 'result': 'fail'}
{'name': 'Dinah Sauve', 'result': 'fail'}
{'name': 'Alica Pasley', 'result': 'fail'}
{'name': 'Elizabet Kleine', 'result': 'fail'}
{'name': 'Tawana Oberg', 'result': 'pass'}
{'name': 'Malisa Jeanes', 'result': 'fail'}
{'name': 'Joel Rueter', 'result': 'pass'}
{'name': 'Tresa Sinha', 'result': 'pass'}
{'name': 'Danika Loeffler', 'result': 'fail'}
{'name': 'Chad Rahe', 'result': 'fail'}
{'name': 'Joaquina Arbuckle', 'result': 'fail'}
{'name': 'Vinnie Auerbach', 'result': 'fail'}
{'name': 'Dusti Lemmond', 'result': 'fail'}
{'name': 'Grady Zemke', 'result': 'pass'}
{'name': 'Vina Matsunaga', 'result': 'fail'}
{'name': 'Rubie Winton', 'result': 'fail'}
{'name': 'Whitley Fears', 'result': 'pass'}
{'name': 'Gena Riccio', 'result': 'pass'}
{'name': 'Kim Xu', 'result': 'fail'}
{'name': 'Merissa Mann', 'result': 'pass'}
{'name': 'Jenise Mcguffie', 'result': 'pass'}
{'name': 'Cody Strouth', 'result': 'fail'}
{'name': 'Harriett Velarde', 'result': 'fail'}
{'name': 'Kam Senters', 'result': 'fail'}
{'name': 'Leonida Lafond', 'result': 'fail'}
{'name': 'Devorah Smartt', 'result': 'fail'}
{'name': 'Leola Lundin', 'result': 'fail'}
{'name': 'Tonia Surace', 'result': 'pass'}
{'name': 'Adrien Renda', 'result': 'fail'}
{'name': 'Efrain Claw', 'result': 'fail'}
{'name': 'Len Treiber', 'result': 'fail'}
{'name': 'Mariela Sherer', 'result': 'pass'}
{'name': 'Echo Pippins', 'result': 'fail'}
{'name': 'Linnie Weigel', 'result': 'fail'}
{'name': 'Santiago Dollins', 'result': 'fail'}
{'name': 'Tonisha Games', 'result': 'fail'}
{'name': 'Timothy Harrod', 'result': 'pass'}
{'name': 'Rae Kohout', 'result': 'pass'}
{'name': 'Brain Lachapelle', 'result': 'fail'}
{'name': 'Toshiko Sabella', 'result': 'fail'}
{'name': 'Keesha Papadopoulos', 'result': 'fail'}
{'name': 'Cassi Heal', 'result': 'fail'}
{'name': 'Osvaldo Hirt', 'result': 'pass'}
{'name': 'Ty Barbieri', 'result': 'fail'}
{'name': 'Ta Sikorski', 'result': 'fail'}
{'name': 'Lucinda Vanderburg', 'result': 'fail'}
{'name': 'Darby Wass', 'result': 'fail'}
{'name': 'Omar Bowdoin', 'result': 'fail'}
{'name': 'Milan Mcgavock', 'result': 'fail'}
{'name': 'Maren Scheider', 'result': 'pass'}
{'name': 'Carli Ector', 'result': 'pass'}
{'name': 'Jaclyn Morado', 'result': 'pass'}
{'name': 'Demarcus Audette', 'result': 'fail'}
{'name': 'Tania Hulett', 'result': 'fail'}
{'name': 'Mercedez Garduno', 'result': 'pass'}
{'name': 'Fleta Duplantis', 'result': 'fail'}
{'name': 'Brittny Warwick', 'result': 'pass'}
{'name': 'Shin Allbright', 'result': 'pass'}
{'name': 'Karry Petrarca', 'result': 'fail'}
{'name': 'Beckie Millington', 'result': 'fail'}
{'name': 'Mikaela Meidinger', 'result': 'pass'}
{'name': 'Flora Duell', 'result': 'pass'}
{'name': 'Nobuko Linzey', 'result': 'pass'}
{'name': 'Gennie Ratner', 'result': 'pass'}
{'name': 'Myrtle Wolfinger', 'result': 'fail'}
{'name': '', 'result': 'fail'}
{'name': 'aimee Zank', 'result': 'fail'}
{'name': 'Aurelia Menendez', 'result': 'fail'}
{'name': 'Corliss Zuk', 'result': 'pass'}
{'name': 'Bao Ziglar', 'result': 'fail'}
{'name': 'Zachary Langlais', 'result': 'pass'}
{'name': 'Wilburn Spiess', 'result': 'pass'}
{'name': 'Jenette Flanders', 'result': 'fail'}
{'name': 'Salena Olmos', 'result': 'fail'}
{'name': 'Daphne Zheng', 'result': 'fail'}
{'name': 'Sanda Ryba', 'result': 'fail'}
{'name': 'Denisha Cast', 'result': 'fail'}
{'name': 'Marcus Blohm', 'result': 'fail'}
{'name': 'Quincy Danaher', 'result': 'pass'}
{'name': 'Jessika Dagenais', 'result': 'pass'}
{'name': 'Alix Sherrill', 'result': 'fail'}
{'name': 'Tambra Mercure', 'result': 'pass'}
{'name': 'Dodie Staller', 'result': 'pass'}
{'name': 'Fletcher Mcconnell', 'result': 'fail'}
{'name': 'Verdell Sowinski', 'result': 'fail'}
{'name': 'Gisela Levin', 'result': 'fail'}
{'name': 'Tressa Schwing', 'result': 'fail'}
{'name': 'Rosana Vales', 'result': 'fail'}
{'name': 'Margart Vitello', 'result': 'fail'}
{'name': 'Tamika Schildgen', 'result': 'fail'}
{'name': 'Jesusa Rickenbacker', 'result': 'fail'}
{'name': 'Rudolph Domingo', 'result': 'fail'}
{'name': 'Jonie Raby', 'result': 'fail'}
{'name': 'Edgar Sarkis', 'result': 'pass'}
{'name': 'Laureen Salomone', 'result': 'fail'}
{'name': 'Gwyneth Garling', 'result': 'fail'}
{'name': 'Kaila Deibler', 'result': 'fail'}
{'name': 'Tandra Meadows', 'result': 'fail'}
{'name': 'Gwen Honig', 'result': 'fail'}
{'name': 'Sadie Jernigan', 'result': 'fail'}
{'name': 'Carli Belvins', 'result': 'fail'}
{'name': 'Synthia Labelle', 'result': 'fail'}
{'name': 'Eugene Magdaleno', 'result': 'fail'}
{'name': 'Meagan Oakes', 'result': 'fail'}
{'name': 'Richelle Siemers', 'result': 'fail'}
{'name': 'Mariette Batdorf', 'result': 'fail'}
{'name': 'Rachell Aman', 'result': 'fail'}
{'name': 'Aleida Elsass', 'result': 'fail'}
{'name': 'Kayce Kenyon', 'result': 'fail'}
{'name': 'Ernestine Macfarland', 'result': 'fail'}
{'name': 'Houston Valenti', 'result': 'fail'}
{'name': 'Terica Brugger', 'result': 'pass'}
{'name': 'Lady Lefevers', 'result': 'fail'}
{'name': 'Kurtis Jiles', 'result': 'fail'}
{'name': 'Barbera Lippman', 'result': 'fail'}
{'name': 'Dinah Sauve', 'result': 'fail'}
{'name': 'Alica Pasley', 'result': 'fail'}
{'name': 'Elizabet Kleine', 'result': 'fail'}
{'name': 'Tawana Oberg', 'result': 'pass'}
{'name': 'Malisa Jeanes', 'result': 'pass'}
{'name': 'Joel Rueter', 'result': 'fail'}
{'name': 'Tresa Sinha', 'result': 'pass'}
{'name': 'Danika Loeffler', 'result': 'fail'}
{'name': 'Chad Rahe', 'result': 'fail'}
{'name': 'Joaquina Arbuckle', 'result': 'fail'}
{'name': 'Vinnie Auerbach', 'result': 'fail'}
{'name': 'Dusti Lemmond', 'result': 'pass'}
{'name': 'Grady Zemke', 'result': 'fail'}
{'name': 'Vina Matsunaga', 'result': 'fail'}
{'name': 'Rubie Winton', 'result': 'fail'}
{'name': 'Whitley Fears', 'result': 'fail'}
{'name': 'Gena Riccio', 'result': 'fail'}
{'name': 'Kim Xu', 'result': 'fail'}
{'name': 'Merissa Mann', 'result': 'fail'}
{'name': 'Jenise Mcguffie', 'result': 'pass'}
{'name': 'Cody Strouth', 'result': 'fail'}
{'name': 'Harriett Velarde', 'result': 'pass'}
{'name': 'Kam Senters', 'result': 'pass'}
{'name': 'Leonida Lafond', 'result': 'fail'}
{'name': 'Devorah Smartt', 'result': 'fail'}
{'name': 'Leola Lundin', 'result': 'pass'}
{'name': 'Tonia Surace', 'result': 'fail'}
{'name': 'Adrien Renda', 'result': 'pass'}
{'name': 'Efrain Claw', 'result': 'pass'}
{'name': 'Len Treiber', 'result': 'fail'}
{'name': 'Mariela Sherer', 'result': 'pass'}
{'name': 'Echo Pippins', 'result': 'fail'}
{'name': 'Linnie Weigel', 'result': 'fail'}
{'name': 'Santiago Dollins', 'result': 'fail'}
{'name': 'Tonisha Games', 'result': 'fail'}
{'name': 'Timothy Harrod', 'result': 'fail'}
{'name': 'Rae Kohout', 'result': 'fail'}

Find the total and average of the exam, quiz and homework and store them in a separate collection.

In [118]:
tot_avg = []

for i in records.find({},{"_id" : 0, "name" :1,"Total" :1, "Percentage" : 1}):
    tot_avg.append(i)
tot_avg

[{'name': 'aimee Zank',
  'Total': 49.11994783171814,
  'Percentage': 16.373315943906046},
 {'name': 'Aurelia Menendez',
  'Total': 184.61969202100374,
  'Percentage': 61.53989734033458},
 {'name': 'Corliss Zuk',
  'Total': 139.61606947126907,
  'Percentage': 46.53868982375636},
 {'name': 'Bao Ziglar',
  'Total': 138.70712252233457,
  'Percentage': 46.23570750744486},
 {'name': 'Zachary Langlais',
  'Total': 203.3963625302728,
  'Percentage': 67.79878751009093},
 {'name': 'Wilburn Spiess',
  'Total': 134.0186975547794,
  'Percentage': 44.67289918492647},
 {'name': 'Jenette Flanders',
  'Total': 147.2203575476617,
  'Percentage': 49.07345251588723},
 {'name': 'Salena Olmos',
  'Total': 229.3959334774732,
  'Percentage': 76.46531115915774},
 {'name': 'Daphne Zheng',
  'Total': 112.71677331754347,
  'Percentage': 37.57225777251449},
 {'name': 'Sanda Ryba',
  'Total': 220.08328118626565,
  'Percentage': 73.36109372875522},
 {'name': 'Denisha Cast',
  'Total': 199.8843572885121,
  'Percentage': 66.62811909617069},
 {'name': 'Marcus Blohm',
  'Total': 248.5091538691126,
  'Percentage': 82.83638462303753},
 {'name': 'Quincy Danaher',
  'Total': 220.31843799333484,
  'Percentage': 73.43947933111161},
 {'name': 'Jessika Dagenais',
  'Total': 275.94947751518237,
  'Percentage': 91.98315917172745},
 {'name': 'Alix Sherrill',
  'Total': 118.48870352377075,
  'Percentage': 39.49623450792358},
 {'name': 'Tambra Mercure',
  'Total': 117.50008641174173,
  'Percentage': 39.16669547058058},
 {'name': 'Dodie Staller',
  'Total': 120.13675287379564,
  'Percentage': 40.045584291265214},
 {'name': 'Fletcher Mcconnell',
  'Total': 218.24398017942121,
  'Percentage': 72.7479933931404},
 {'name': 'Verdell Sowinski',
  'Total': 228.46404278930964,
  'Percentage': 76.15468092976988},
 {'name': 'Gisela Levin',
  'Total': 138.53337737572195,
  'Percentage': 46.17779245857398},
 {'name': 'Tressa Schwing',
  'Total': 195.4072727218341,
  'Percentage': 65.1357575739447},
 {'name': 'Rosana Vales',
  'Total': 180.75828734596254,
  'Percentage': 60.25276244865418},
 {'name': 'Margart Vitello',
  'Total': 182.00563535570944,
  'Percentage': 60.66854511856982},
 {'name': 'Tamika Schildgen',
  'Total': 193.52293165444934,
  'Percentage': 64.50764388481645},
 {'name': 'Jesusa Rickenbacker',
  'Total': 149.10807613148083,
  'Percentage': 49.70269204382694},
 {'name': 'Rudolph Domingo',
  'Total': 148.54969223180623,
  'Percentage': 49.51656407726875},
 {'name': 'Jonie Raby',
  'Total': 139.96370462720506,
  'Percentage': 46.65456820906835},
 {'name': 'Edgar Sarkis',
  'Total': 82.65605000904621,
  'Percentage': 27.55201666968207},
 {'name': 'Laureen Salomone',
  'Total': 93.67011710439672,
  'Percentage': 31.223372368132242},
 {'name': 'Gwyneth Garling',
  'Total': 152.01111322298112,
  'Percentage': 50.67037107432704},
 {'name': 'Kaila Deibler',
  'Total': 139.48229678140956,
  'Percentage': 46.49409892713652},
 {'name': 'Tandra Meadows',
  'Total': 150.89635115040903,
  'Percentage': 50.29878371680301},
 {'name': 'Gwen Honig',
  'Total': 263.26630272241187,
  'Percentage': 87.75543424080395},
 {'name': 'Sadie Jernigan',
  'Total': 158.6873725512847,
  'Percentage': 52.895790850428234},
 {'name': 'Carli Belvins',
  'Total': 163.84548928047394,
  'Percentage': 54.61516309349131},
 {'name': 'Synthia Labelle',
  'Total': 137.7409456810277,
  'Percentage': 45.91364856034257},
 {'name': 'Eugene Magdaleno',
  'Total': 219.00355238869096,
  'Percentage': 73.00118412956365},
 {'name': 'Meagan Oakes',
  'Total': 193.9294745099881,
  'Percentage': 64.64315816999603},
 {'name': 'Richelle Siemers',
  'Total': 182.2378812069286,
  'Percentage': 60.74596040230953},
 {'name': 'Mariette Batdorf',
  'Total': 156.18768410864072,
  'Percentage': 52.062561369546906},
 {'name': 'Rachell Aman',
  'Total': 180.20639736938892,
  'Percentage': 60.068799123129644},
 {'name': 'Aleida Elsass',
  'Total': 191.3374155242169,
  'Percentage': 63.7791385080723},
 {'name': 'Kayce Kenyon',
  'Total': 169.44237645698738,
  'Percentage': 56.48079215232912},
 {'name': 'Ernestine Macfarland',
  'Total': 124.72878418014199,
  'Percentage': 41.57626139338066},
 {'name': 'Houston Valenti',
  'Total': 114.15826509656077,
  'Percentage': 38.05275503218692},
 {'name': 'Terica Brugger',
  'Total': 102.75054456167354,
  'Percentage': 34.250181520557845},
 {'name': 'Lady Lefevers',
  'Total': 131.29270853967182,
  'Percentage': 43.76423617989061},
 {'name': 'Kurtis Jiles',
  'Total': 147.7356498111623,
  'Percentage': 49.24521660372076},
 {'name': 'Barbera Lippman',
  'Total': 206.96494520146337,
  'Percentage': 68.98831506715446},
 {'name': 'Dinah Sauve',
  'Total': 183.2179783546083,
  'Percentage': 61.072659451536104},
 {'name': 'Alica Pasley',
  'Total': 168.7205264204154,
  'Percentage': 56.2401754734718},
 {'name': 'Elizabet Kleine',
  'Total': 200.94891534204805,
  'Percentage': 66.98297178068269},
 {'name': 'Tawana Oberg',
  'Total': 266.9957822154724,
  'Percentage': 88.99859407182413},
 {'name': 'Malisa Jeanes',
  'Total': 121.1518349933377,
  'Percentage': 40.38394499777923},
 {'name': 'Joel Rueter',
  'Total': 242.0364415445718,
  'Percentage': 80.6788138481906},
 {'name': 'Tresa Sinha',
  'Total': 244.50239963952316,
  'Percentage': 81.50079987984105},
 {'name': 'Danika Loeffler',
  'Total': 119.00689284424402,
  'Percentage': 39.668964281414674},
 {'name': 'Chad Rahe',
  'Total': 163.19418005225754,
  'Percentage': 54.398060017419176},
 {'name': 'Joaquina Arbuckle',
  'Total': 120.66923159080469,
  'Percentage': 40.223077196934895},
 {'name': 'Vinnie Auerbach',
  'Total': 131.55784600976585,
  'Percentage': 43.85261533658862},
 {'name': 'Dusti Lemmond',
  'Total': 182.36423465019507,
  'Percentage': 60.78807821673169},
 {'name': 'Grady Zemke',
  'Total': 197.34049948667015,
  'Percentage': 65.78016649555671},
 {'name': 'Vina Matsunaga',
  'Total': 132.2872844609489,
  'Percentage': 44.09576148698297},
 {'name': 'Rubie Winton',
  'Total': 72.74345907466646,
  'Percentage': 24.247819691555488},
 {'name': 'Whitley Fears',
  'Total': 268.6463713649928,
  'Percentage': 89.54879045499759},
 {'name': 'Gena Riccio',
  'Total': 177.76002098364026,
  'Percentage': 59.25334032788009},
 {'name': 'Kim Xu',
  'Total': 94.82481083119796,
  'Percentage': 31.608270277065987},
 {'name': 'Merissa Mann',
  'Total': 222.43538108594768,
  'Percentage': 74.14512702864923},
 {'name': 'Jenise Mcguffie',
  'Total': 182.34150787254515,
  'Percentage': 60.780502624181715},
 {'name': 'Cody Strouth',
  'Total': 202.4848718127078,
  'Percentage': 67.4949572709026},
 {'name': 'Harriett Velarde',
  'Total': 176.07490979439646,
  'Percentage': 58.691636598132156},
 {'name': 'Kam Senters',
  'Total': 178.913172052241,
  'Percentage': 59.63772401741367},
 {'name': 'Leonida Lafond',
  'Total': 206.92216095602325,
  'Percentage': 68.97405365200775},
 {'name': 'Devorah Smartt',
  'Total': 132.19316603930335,
  'Percentage': 44.06438867976778},
 {'name': 'Leola Lundin',
  'Total': 216.63267038170724,
  'Percentage': 72.21089012723574},
 {'name': 'Tonia Surace',
  'Total': 201.82584001807396,
  'Percentage': 67.27528000602466},
 {'name': 'Adrien Renda',
  'Total': 147.47020593990004,
  'Percentage': 49.15673531330001},
 {'name': 'Efrain Claw',
  'Total': 175.4476010143183,
  'Percentage': 58.482533671439434},
 {'name': 'Len Treiber',
  'Total': 116.94520656066045,
  'Percentage': 38.98173552022015},
 {'name': 'Mariela Sherer',
  'Total': 204.9282017860081,
  'Percentage': 68.30940059533603},
 {'name': 'Echo Pippins',
  'Total': 205.47216171064758,
  'Percentage': 68.49072057021586},
 {'name': 'Linnie Weigel',
  'Total': 171.94196655853844,
  'Percentage': 57.313988852846144},
 {'name': 'Santiago Dollins',
  'Total': 181.00006173963334,
  'Percentage': 60.33335391321111},
 {'name': 'Tonisha Games',
  'Total': 131.11934974450202,
  'Percentage': 43.706449914834},
 {'name': 'Timothy Harrod',
  'Total': 216.29819060759476,
  'Percentage': 72.09939686919826},
 {'name': 'Rae Kohout',
  'Total': 178.820098003648,
  'Percentage': 59.60669933454934},
 {'name': 'Brain Lachapelle',
  'Total': 135.07862363042534,
  'Percentage': 45.02620787680845},
 {'name': 'Toshiko Sabella',
  'Total': 90.29289206681383,
  'Percentage': 30.097630688937944},
 {'name': 'Keesha Papadopoulos',
  'Total': 183.8870127743818,
  'Percentage': 61.29567092479393},
 {'name': 'Cassi Heal',
  'Total': 106.93494167763413,
  'Percentage': 35.644980559211376},
 {'name': 'Osvaldo Hirt',
  'Total': 185.53797432894692,
  'Percentage': 61.8459914429823},
 {'name': 'Ty Barbieri',
  'Total': 206.94394766986875,
  'Percentage': 68.98131588995625},
 {'name': 'Ta Sikorski',
  'Total': 115.74213180964733,
  'Percentage': 38.58071060321578},
 {'name': 'Lucinda Vanderburg',
  'Total': 114.55089488600422,
  'Percentage': 38.183631628668074},
 {'name': 'Darby Wass',
  'Total': 155.7771022790884,
  'Percentage': 51.925700759696134},
 {'name': 'Omar Bowdoin',
  'Total': 122.70623232239147,
  'Percentage': 40.90207744079716},
 {'name': 'Milan Mcgavock',
  'Total': 104.19377141035017,
  'Percentage': 34.73125713678339},
 {'name': 'Maren Scheider',
  'Total': 231.17881123988667,
  'Percentage': 77.0596037466289},
 {'name': 'Carli Ector',
  'Total': 244.82763178118853,
  'Percentage': 81.60921059372951},
 {'name': 'Jaclyn Morado',
  'Total': 174.5461576760983,
  'Percentage': 58.18205255869943},
 {'name': 'Demarcus Audette',
  'Total': 131.27751820054362,
  'Percentage': 43.75917273351454},
 {'name': 'Tania Hulett',
  'Total': 155.30833228670144,
  'Percentage': 51.769444095567145},
 {'name': 'Mercedez Garduno',
  'Total': 175.59251820500876,
  'Percentage': 58.53083940166959},
 {'name': 'Fleta Duplantis',
  'Total': 178.1433701618344,
  'Percentage': 59.38112338727814},
 {'name': 'Brittny Warwick',
  'Total': 247.51315928921287,
  'Percentage': 82.50438642973762},
 {'name': 'Shin Allbright',
  'Total': 236.5473215674034,
  'Percentage': 78.84910718913447},
 {'name': 'Karry Petrarca',
  'Total': 58.45858761680128,
  'Percentage': 19.486195872267093},
 {'name': 'Beckie Millington',
  'Total': 129.29870077731468,
  'Percentage': 43.09956692577156},
 {'name': 'Mikaela Meidinger',
  'Total': 211.94374606058196,
  'Percentage': 70.64791535352732},
 {'name': 'Flora Duell',
  'Total': 156.75611063955935,
  'Percentage': 52.252036879853115},
 {'name': 'Nobuko Linzey',
  'Total': 173.43955303906787,
  'Percentage': 57.81318434635596},
 {'name': 'Gennie Ratner',
  'Total': 208.03498281392888,
  'Percentage': 69.34499427130963},
 {'name': 'Myrtle Wolfinger',
  'Total': 203.79119045268433,
  'Percentage': 67.93039681756144},
 {'name': '', 'Total': 158.1297878869123, 'Percentage': 52.70992929563744},
 {'name': 'aimee Zank',
  'Total': 130.9721943324432,
  'Percentage': 43.6573981108144},
 {'name': 'Aurelia Menendez',
  'Total': 105.10579094395169,
  'Percentage': 35.035263647983896},
 {'name': 'Corliss Zuk',
  'Total': 221.3468479915618,
  'Percentage': 73.78228266385393},
 {'name': 'Bao Ziglar',
  'Total': 154.0475585018162,
  'Percentage': 51.34918616727207},
 {'name': 'Zachary Langlais',
  'Total': 205.6587944217254,
  'Percentage': 68.55293147390846},
 {'name': 'Wilburn Spiess',
  'Total': 210.2915152985196,
  'Percentage': 70.0971717661732},
 {'name': 'Jenette Flanders',
  'Total': 107.87159055374062,
  'Percentage': 35.95719685124687},
 {'name': 'Salena Olmos',
  'Total': 110.68556639219787,
  'Percentage': 36.89518879739929},
 {'name': 'Daphne Zheng',
  'Total': 171.68464931123447,
  'Percentage': 57.22821643707815},
 {'name': 'Sanda Ryba',
  'Total': 71.27146027282822,
  'Percentage': 23.757153424276073},
 {'name': 'Denisha Cast',
  'Total': 118.2341215780863,
  'Percentage': 39.4113738593621},
 {'name': 'Marcus Blohm',
  'Total': 137.0342890305606,
  'Percentage': 45.678096343520195},
 {'name': 'Quincy Danaher',
  'Total': 202.62862134543295,
  'Percentage': 67.54287378181098},
 {'name': 'Jessika Dagenais',
  'Total': 263.3989659226766,
  'Percentage': 87.79965530755887},
 {'name': 'Alix Sherrill',
  'Total': 82.279654851893,
  'Percentage': 27.426551617297665},
 {'name': 'Tambra Mercure',
  'Total': 195.46779056021484,
  'Percentage': 65.15593018673827},
 {'name': 'Dodie Staller',
  'Total': 199.56471905226374,
  'Percentage': 66.52157301742125},
 {'name': 'Fletcher Mcconnell',
  'Total': 149.26675330972444,
  'Percentage': 49.755584436574814},
 {'name': 'Verdell Sowinski',
  'Total': 145.68727217339975,
  'Percentage': 48.562424057799916},
 {'name': 'Gisela Levin',
  'Total': 123.94644554660489,
  'Percentage': 41.315481848868295},
 {'name': 'Tressa Schwing',
  'Total': 166.0992291248508,
  'Percentage': 55.366409708283605},
 {'name': 'Rosana Vales',
  'Total': 112.23313600351938,
  'Percentage': 37.41104533450646},
 {'name': 'Margart Vitello',
  'Total': 166.81836101629523,
  'Percentage': 55.60612033876507},
 {'name': 'Tamika Schildgen',
  'Total': 159.53213257952987,
  'Percentage': 53.17737752650996},
 {'name': 'Jesusa Rickenbacker',
  'Total': 115.54875333859893,
  'Percentage': 38.51625111286631},
 {'name': 'Rudolph Domingo',
  'Total': 160.0864123492324,
  'Percentage': 53.36213744974413},
 {'name': 'Jonie Raby',
  'Total': 102.86145390316119,
  'Percentage': 34.28715130105373},
 {'name': 'Edgar Sarkis',
  'Total': 199.81866315163785,
  'Percentage': 66.60622105054595},
 {'name': 'Laureen Salomone',
  'Total': 153.09832674227243,
  'Percentage': 51.03277558075748},
 {'name': 'Gwyneth Garling',
  'Total': 152.28848205662155,
  'Percentage': 50.76282735220718},
 {'name': 'Kaila Deibler',
  'Total': 183.09592918689077,
  'Percentage': 61.03197639563026},
 {'name': 'Tandra Meadows',
  'Total': 87.5629850401662,
  'Percentage': 29.1876616800554},
 {'name': 'Gwen Honig',
  'Total': 201.4156031244819,
  'Percentage': 67.1385343748273},
 {'name': 'Sadie Jernigan',
  'Total': 141.02791381651215,
  'Percentage': 47.00930460550405},
 {'name': 'Carli Belvins',
  'Total': 174.61862132435388,
  'Percentage': 58.20620710811796},
 {'name': 'Synthia Labelle',
  'Total': 141.50995457365985,
  'Percentage': 47.16998485788662},
 {'name': 'Eugene Magdaleno',
  'Total': 126.52248166745107,
  'Percentage': 42.174160555817025},
 {'name': 'Meagan Oakes',
  'Total': 186.33086651795293,
  'Percentage': 62.11028883931764},
 {'name': 'Richelle Siemers',
  'Total': 139.60355242003698,
  'Percentage': 46.53451747334566},
 {'name': 'Mariette Batdorf',
  'Total': 182.97224595186646,
  'Percentage': 60.99074865062215},
 {'name': 'Rachell Aman',
  'Total': 164.66123279589482,
  'Percentage': 54.887077598631606},
 {'name': 'Aleida Elsass',
  'Total': 167.56608209438596,
  'Percentage': 55.855360698128656},
 {'name': 'Kayce Kenyon',
  'Total': 144.78774966244362,
  'Percentage': 48.26258322081454},
 {'name': 'Ernestine Macfarland',
  'Total': 160.1015626796132,
  'Percentage': 53.36718755987107},
 {'name': 'Houston Valenti',
  'Total': 165.92615898115974,
  'Percentage': 55.30871966038658},
 {'name': 'Terica Brugger',
  'Total': 251.40459832855427,
  'Percentage': 83.80153277618476},
 {'name': 'Lady Lefevers',
  'Total': 188.71235039768163,
  'Percentage': 62.90411679922721},
 {'name': 'Kurtis Jiles',
  'Total': 169.36123484704996,
  'Percentage': 56.45374494901665},
 {'name': 'Barbera Lippman',
  'Total': 123.87383657752201,
  'Percentage': 41.29127885917401},
 {'name': 'Dinah Sauve',
  'Total': 75.2279417690119,
  'Percentage': 25.075980589670635},
 {'name': 'Alica Pasley',
  'Total': 165.63284138505927,
  'Percentage': 55.21094712835309},
 {'name': 'Elizabet Kleine',
  'Total': 128.08011084675638,
  'Percentage': 42.693370282252125},
 {'name': 'Tawana Oberg',
  'Total': 243.58164706138706,
  'Percentage': 81.19388235379569},
 {'name': 'Malisa Jeanes',
  'Total': 187.97482237036616,
  'Percentage': 62.658274123455385},
 {'name': 'Joel Rueter',
  'Total': 66.68048171963756,
  'Percentage': 22.226827239879185},
 {'name': 'Tresa Sinha',
  'Total': 204.71743269051856,
  'Percentage': 68.23914423017285},
 {'name': 'Danika Loeffler',
  'Total': 177.90923607877596,
  'Percentage': 59.30307869292532},
 {'name': 'Chad Rahe',
  'Total': 181.46853696091893,
  'Percentage': 60.48951232030631},
 {'name': 'Joaquina Arbuckle',
  'Total': 224.32072038808982,
  'Percentage': 74.7735734626966},
 {'name': 'Vinnie Auerbach',
  'Total': 154.92533590812064,
  'Percentage': 51.641778636040215},
 {'name': 'Dusti Lemmond',
  'Total': 193.43589837735124,
  'Percentage': 64.47863279245041},
 {'name': 'Grady Zemke',
  'Total': 106.35844585670458,
  'Percentage': 35.45281528556819},
 {'name': 'Vina Matsunaga',
  'Total': 133.82960397641585,
  'Percentage': 44.60986799213862},
 {'name': 'Rubie Winton',
  'Total': 216.40738876682235,
  'Percentage': 72.13579625560745},
 {'name': 'Whitley Fears',
  'Total': 177.765433771189,
  'Percentage': 59.255144590396334},
 {'name': 'Gena Riccio',
  'Total': 201.16314710069156,
  'Percentage': 67.05438236689719},
 {'name': 'Kim Xu',
  'Total': 160.22762084530626,
  'Percentage': 53.40920694843542},
 {'name': 'Merissa Mann',
  'Total': 100.71792724568269,
  'Percentage': 33.57264241522756},
 {'name': 'Jenise Mcguffie',
  'Total': 247.055709123218,
  'Percentage': 82.35190304107267},
 {'name': 'Cody Strouth',
  'Total': 201.24422489578706,
  'Percentage': 67.08140829859569},
 {'name': 'Harriett Velarde',
  'Total': 220.21398004688467,
  'Percentage': 73.40466001562822},
 {'name': 'Kam Senters',
  'Total': 164.057897124202,
  'Percentage': 54.68596570806733},
 {'name': 'Leonida Lafond',
  'Total': 98.45768055586619,
  'Percentage': 32.8192268519554},
 {'name': 'Devorah Smartt',
  'Total': 100.39268848940415,
  'Percentage': 33.46422949646805},
 {'name': 'Leola Lundin',
  'Total': 176.30791809119162,
  'Percentage': 58.76930603039721},
 {'name': 'Tonia Surace',
  'Total': 181.79622614209114,
  'Percentage': 60.598742047363714},
 {'name': 'Adrien Renda',
  'Total': 227.1544319588548,
  'Percentage': 75.71814398628493},
 {'name': 'Efrain Claw',
  'Total': 252.83317597388418,
  'Percentage': 84.27772532462807},
 {'name': 'Len Treiber',
  'Total': 182.73801465117188,
  'Percentage': 60.91267155039063},
 {'name': 'Mariela Sherer',
  'Total': 159.69068323680995,
  'Percentage': 53.230227745603315},
 {'name': 'Echo Pippins',
  'Total': 133.2728581307499,
  'Percentage': 44.4242860435833},
 {'name': 'Linnie Weigel',
  'Total': 154.97337291894834,
  'Percentage': 51.65779097298278},
 {'name': 'Santiago Dollins',
  'Total': 164.46610025223168,
  'Percentage': 54.82203341741056},
 {'name': 'Tonisha Games',
  'Total': 148.83413523189756,
  'Percentage': 49.61137841063252},
 {'name': 'Timothy Harrod',
  'Total': 97.28287057232586,
  'Percentage': 32.42762352410862},
 {'name': 'Rae Kohout',
  'Total': 160.5986170288919,
  'Percentage': 53.53287234296397}]

In [120]:
records1 = db["Total_Percentage"]

In [121]:
for i in range(len(tot_avg)):
    records1.insert_one(tot_avg[i])

Create a new collection which consists of students who scored below average and above 40% in all the categories.

In [139]:
records2 = db["avg_students"]

In [140]:
x = records.aggregate(
[{
    "$match" :

        {"$and" : [ {"Exam" : { "$gte" : 40, "$lte" : 70 } }, {"Quiz" : { "$gte" : 40, "$lte" : 70 } },
                   {"HomeWork" : { "$gte" : 40, "$lte" : 70 } }]


    }
}])
avg_stu = []
for i in x:
    records2.insert_one(i)

In [142]:
for i in records2.find():
    print(i)

{'_id': ObjectId('6231ddd19855c49b8d7536d3'), 'name': 'Gena Riccio', 'Exam': 67.58395308948619, 'Quiz': 67.2413500951588, 'HomeWork': 42.93471779899529, 'Total': 177.76002098364026, 'Percentage': 59.25334032788009}
{'_id': ObjectId('6231ddd79855c49b8d7536e7'), 'name': 'Rae Kohout', 'Exam': 63.86894250781692, 'Quiz': 55.81549538273672, 'HomeWork': 59.13566011309437, 'Total': 178.820098003648, 'Percentage': 59.60669933454934}
{'_id': ObjectId('6231dddd9855c49b8d7536ff'), 'name': 'Flora Duell', 'Exam': 40.68238966626067, 'Quiz': 46.77972040308903, 'HomeWork': 69.29400057020965, 'Total': 156.75611063955935, 'Percentage': 52.252036879853115}
{'_id': ObjectId('6231ddde9855c49b8d753700'), 'name': 'Nobuko Linzey', 'Exam': 67.40792606687442, 'Quiz': 58.58331128403415, 'HomeWork': 47.44831568815929, 'Total': 173.43955303906787, 'Percentage': 57.81318434635596}
{'_id': ObjectId('6231ddf19855c49b8d75374b'), 'name': 'Kam Senters', 'Exam': 49.8822537074033, 'Quiz': 45.29515361387067, 'HomeWork': 68.88048980292801, 'Total': 164.057897124202, 'Percentage': 54.68596570806733}

Create a new collection which consists of students who scored below the fail mark in all the categories.

In [144]:
records3 = db["Failed_students"]

In [145]:
x = records.aggregate(
[{
    "$match" :

        {"$and" : [ {"Exam" : {"$lte" : 40 }}, {"Quiz" : {"$lte" : 40 } },
                   {"HomeWork" : {"$lte" : 40 } }]


    }
}])

for i in x:
    records3.insert_one(i)

In [147]:
for i in records3.find():
    print(i)

{'_id': ObjectId('6231ddbd9855c49b8d753692'), 'name': 'aimee Zank', 'Exam': 1.463179736705023, 'Quiz': 11.78273309957772, 'HomeWork': 35.8740349954354, 'Total': 49.11994783171814, 'Percentage': 16.373315943906046}

Create a new collection which consists of students who scored above pass mark in all the categories.

In [148]:
records4 = db["Passed_students"]

In [149]:
x = records.aggregate(
[{
    "$match" :

        {"$and" : [ {"Exam" : {"$gte" : 40 }}, {"Quiz" : {"$gte" : 40 } },
                   {"HomeWork" : {"$gte" : 40 } }]


    }
}])

for i in x:
    records4.insert_one(i)

In [150]:
for i in records4.find():
    print(i)

{'_id': ObjectId('6231ddbe9855c49b8d753693'), 'name': 'Aurelia Menendez', 'Exam': 60.06045071030959, 'Quiz': 52.79790691903873, 'HomeWork': 71.76133439165544, 'Total': 184.61969202100374, 'Percentage': 61.53989734033458}
{'_id': ObjectId('6231ddc09855c49b8d753699'), 'name': 'Salena Olmos', 'Exam': 90.37826509157176, 'Quiz': 42.48780666956811, 'HomeWork': 96.52986171633331, 'Total': 229.3959334774732, 'Percentage': 76.46531115915774}
{'_id': ObjectId('6231ddc19855c49b8d75369c'), 'name': 'Denisha Cast', 'Exam': 45.61876862259409, 'Quiz': 98.35723209418343, 'HomeWork': 55.90835657173456, 'Total': 199.8843572885121, 'Percentage': 66.62811909617069}
{'_id': ObjectId('6231ddc19855c49b8d75369d'), 'name': 'Marcus Blohm', 'Exam': 78.42617835651868, 'Quiz': 82.58372817930675, 'HomeWork': 87.49924733328717, 'Total': 248.5091538691126, 'Percentage': 82.83638462303753}
{'_id': ObjectId('6231ddc19855c49b8d75369e'), 'name': 'Quincy Danaher', 'Exam': 54.29841278520669, 'Quiz': 85.61270164694737, 'HomeWork': 80.40732356118075, 'Total': 220.31843799333484, 'Percentage': 73.43947933111161}
{'_id': ObjectId('6231ddc29855c49b8d75369f'), 'name': 'Jessika Dagenais', 'Exam': 90.47179954427436, 'Quiz': 90.3001402468489, 'HomeWork': 95.17753772405909, 'Total': 275.94947751518237, 'Percentage': 91.98315917172745}
{'_id': ObjectId('6231ddc39855c49b8d7536a4'), 'name': 'Verdell Sowinski', 'Exam': 62.12870233109035, 'Quiz': 84.74586220889356, 'HomeWork': 81.58947824932574, 'Total': 228.46404278930964, 'Percentage': 76.15468092976988}
{'_id': ObjectId('6231ddc49855c49b8d7536a6'), 'name': 'Tressa Schwing', 'Exam': 42.17439799514388, 'Quiz': 71.99314840599558, 'HomeWork': 81.23972632069464, 'Total': 195.4072727218341, 'Percentage': 65.1357575739447}
{'_id': ObjectId('6231ddc59855c49b8d7536a9'), 'name': 'Tamika Schildgen', 'Exam': 45.65432764125526, 'Quiz': 64.32927049658846, 'HomeWork': 83.53933351660562, 'Total': 193.52293165444934, 'Percentage': 64.50764388481645}
{'_id': ObjectId('6231ddc79855c49b8d7536b2'), 'name': 'Gwen Honig', 'Exam': 87.14345376886205, 'Quiz': 99.45824441135635, 'HomeWork': 76.66460454219344, 'Total': 263.26630272241187, 'Percentage': 87.75543424080395}
{'_id': ObjectId('6231ddc89855c49b8d7536b6'), 'name': 'Eugene Magdaleno', 'Exam': 73.055900093666, 'Quiz': 79.85621560462026, 'HomeWork': 66.09143669040472, 'Total': 219.00355238869096, 'Percentage': 73.00118412956365}
{'_id': ObjectId('6231ddcd9855c49b8d7536c6'), 'name': 'Tawana Oberg', 'Exam': 80.59006098671075, 'Quiz': 93.28438118988183, 'HomeWork': 93.12134003887978, 'Total': 266.9957822154724, 'Percentage': 88.99859407182413}
{'_id': ObjectId('6231ddce9855c49b8d7536c8'), 'name': 'Joel Rueter', 'Exam': 87.53636893952853, 'Quiz': 92.70974674256513, 'HomeWork': 61.79032586247813, 'Total': 242.0364415445718, 'Percentage': 80.6788138481906}
{'_id': ObjectId('6231ddce9855c49b8d7536c9'), 'name': 'Tresa Sinha', 'Exam': 94.93136959210354, 'Quiz': 72.32226123565266, 'HomeWork': 77.248768811767, 'Total': 244.50239963952316, 'Percentage': 81.50079987984105}
{'_id': ObjectId('6231ddd09855c49b8d7536cf'), 'name': 'Grady Zemke', 'Exam': 51.91561300267121, 'Quiz': 50.08349374829509, 'HomeWork': 95.34139273570386, 'Total': 197.34049948667015, 'Percentage': 65.78016649555671}
{'_id': ObjectId('6231ddd19855c49b8d7536d2'), 'name': 'Whitley Fears', 'Exam': 89.61845831842888, 'Quiz': 82.44879156010508, 'HomeWork': 96.57912148645883, 'Total': 268.6463713649928, 'Percentage': 89.54879045499759}
{'_id': ObjectId('6231ddd19855c49b8d7536d3'), 'name': 'Gena Riccio', 'Exam': 67.58395308948619, 'Quiz': 67.2413500951588, 'HomeWork': 42.93471779899529, 'Total': 177.76002098364026, 'Percentage': 59.25334032788009}
{'_id': ObjectId('6231ddd19855c49b8d7536d5'), 'name': 'Merissa Mann', 'Exam': 75.1949733626123, 'Quiz': 52.56522605123723, 'HomeWork': 94.67518167209815, 'Total': 222.43538108594768, 'Percentage': 74.14512702864923}
{'_id': ObjectId('6231ddd29855c49b8d7536d6'), 'name': 'Jenise Mcguffie', 'Exam': 40.15210496060384, 'Quiz': 90.60219950183566, 'HomeWork': 51.58720341010564, 'Total': 182.34150787254515, 'Percentage': 60.780502624181715}
{'_id': ObjectId('6231ddd49855c49b8d7536dd'), 'name': 'Tonia Surace', 'Exam': 80.93655069496523, 'Quiz': 79.54620208144452, 'HomeWork': 41.34308724166419, 'Total': 201.82584001807396, 'Percentage': 67.27528000602466}
{'_id': ObjectId('6231ddd59855c49b8d7536e1'), 'name': 'Mariela Sherer', 'Exam': 61.20158144877323, 'Quiz': 52.75657259917104, 'HomeWork': 90.97004773806381, 'Total': 204.9282017860081, 'Percentage': 68.30940059533603}
{'_id': ObjectId('6231ddd79855c49b8d7536e6'), 'name': 'Timothy Harrod', 'Exam': 93.23020013495737, 'Quiz': 49.06010347848443, 'HomeWork': 74.00788699415295, 'Total': 216.29819060759476, 'Percentage': 72.09939686919826}
{'_id': ObjectId('6231ddd79855c49b8d7536e7'), 'name': 'Rae Kohout', 'Exam': 63.86894250781692, 'Quiz': 55.81549538273672, 'HomeWork': 59.13566011309437, 'Total': 178.820098003648, 'Percentage': 59.60669933454934}
{'_id': ObjectId('6231ddd89855c49b8d7536ec'), 'name': 'Osvaldo Hirt', 'Exam': 67.44931456608883, 'Quiz': 41.77986504201782, 'HomeWork': 76.30879472084027, 'Total': 185.53797432894692, 'Percentage': 61.8459914429823}
{'_id': ObjectId('6231ddda9855c49b8d7536f3'), 'name': 'Maren Scheider', 'Exam': 94.4329121733663, 'Quiz': 77.28263690107663, 'HomeWork': 59.46326216544371, 'Total': 231.17881123988667, 'Percentage': 77.0596037466289}
{'_id': ObjectId('6231ddda9855c49b8d7536f4'), 'name': 'Carli Ector', 'Exam': 88.18040268522668, 'Quiz': 60.3111085581054, 'HomeWork': 96.33612053785647, 'Total': 244.82763178118853, 'Percentage': 81.60921059372951}
{'_id': ObjectId('6231ddda9855c49b8d7536f5'), 'name': 'Jaclyn Morado', 'Exam': 70.27627082122453, 'Quiz': 56.78470387064279, 'HomeWork': 47.48518298423097, 'Total': 174.5461576760983, 'Percentage': 58.18205255869943}
{'_id': ObjectId('6231dddb9855c49b8d7536f8'), 'name': 'Mercedez Garduno', 'Exam': 49.52877007656483, 'Quiz': 44.55505066212384, 'HomeWork': 81.50869746632009, 'Total': 175.59251820500876, 'Percentage': 58.53083940166959}
{'_id': ObjectId('6231dddc9855c49b8d7536fa'), 'name': 'Brittny Warwick', 'Exam': 69.54399888097534, 'Quiz': 82.00469934215849, 'HomeWork': 95.96446106607902, 'Total': 247.51315928921287, 'Percentage': 82.50438642973762}
{'_id': ObjectId('6231dddc9855c49b8d7536fb'), 'name': 'Shin Allbright', 'Exam': 62.28388941877533, 'Quiz': 85.26863799439475, 'HomeWork': 88.9947941542333, 'Total': 236.5473215674034, 'Percentage': 78.84910718913447}
{'_id': ObjectId('6231dddd9855c49b8d7536fe'), 'name': 'Mikaela Meidinger', 'Exam': 63.75595052560389, 'Quiz': 59.52298111997963, 'HomeWork': 88.66481441499843, 'Total': 211.94374606058196, 'Percentage': 70.64791535352732}
{'_id': ObjectId('6231dddd9855c49b8d7536ff'), 'name': 'Flora Duell', 'Exam': 40.68238966626067, 'Quiz': 46.77972040308903, 'HomeWork': 69.29400057020965, 'Total': 156.75611063955935, 'Percentage': 52.252036879853115}
{'_id': ObjectId('6231ddde9855c49b8d753700'), 'name': 'Nobuko Linzey', 'Exam': 67.40792606687442, 'Quiz': 58.58331128403415, 'HomeWork': 47.44831568815929, 'Total': 173.43955303906787, 'Percentage': 57.81318434635596}
{'_id': ObjectId('6231ddde9855c49b8d753701'), 'name': 'Gennie Ratner', 'Exam': 62.74309964110307, 'Quiz': 92.18013849235186, 'HomeWork': 53.11174468047395, 'Total': 208.03498281392888, 'Percentage': 69.34499427130963}
{'_id': ObjectId('6231dddf9855c49b8d753706'), 'name': 'Corliss Zuk', 'Exam': 76.45468797439878, 'Quiz': 53.02642890026489, 'HomeWork': 91.86573111689813, 'Total': 221.3468479915618, 'Percentage': 73.78228266385393}
{'_id': ObjectId('6231dde09855c49b8d753708'), 'name': 'Zachary Langlais', 'Exam': 62.20457822364115, 'Quiz': 61.03733414415722, 'HomeWork': 82.41688205392703, 'Total': 205.6587944217254, 'Percentage': 68.55293147390846}
{'_id': ObjectId('6231dde09855c49b8d753709'), 'name': 'Wilburn Spiess', 'Exam': 52.36963021569788, 'Quiz': 96.5715450678789, 'HomeWork': 61.35034001494281, 'Total': 210.2915152985196, 'Percentage': 70.0971717661732}
{'_id': ObjectId('6231dde29855c49b8d753710'), 'name': 'Quincy Danaher', 'Exam': 40.53136904234401, 'Quiz': 83.09270171511093, 'HomeWork': 79.004550587978, 'Total': 202.62862134543295, 'Percentage': 67.54287378181098}
{'_id': ObjectId('6231dde29855c49b8d753711'), 'name': 'Jessika Dagenais', 'Exam': 96.93459855769822, 'Quiz': 95.6756371543187, 'HomeWork': 70.7887302106597, 'Total': 263.3989659226766, 'Percentage': 87.79965530755887}
{'_id': ObjectId('6231dde39855c49b8d753713'), 'name': 'Tambra Mercure', 'Exam': 62.61423873241083, 'Quiz': 47.64776674251425, 'HomeWork': 85.20578508528978, 'Total': 195.46779056021484, 'Percentage': 65.15593018673827}
{'_id': ObjectId('6231dde39855c49b8d753714'), 'name': 'Dodie Staller', 'Exam': 52.16051124848157, 'Quiz': 83.51563143820728, 'HomeWork': 63.88857636557489, 'Total': 199.56471905226374, 'Percentage': 66.52157301742125}
{'_id': ObjectId('6231dde69855c49b8d75371f'), 'name': 'Edgar Sarkis', 'Exam': 65.99888014434269, 'Quiz': 58.75598946266268, 'HomeWork': 75.06379354463246, 'Total': 199.81866315163785, 'Percentage': 66.60622105054595}
{'_id': ObjectId('6231ddea9855c49b8d753731'), 'name': 'Terica Brugger', 'Exam': 97.822030541043, 'Quiz': 91.56280485763772, 'HomeWork': 62.01976292987356, 'Total': 251.40459832855427, 'Percentage': 83.80153277618476}
{'_id': ObjectId('6231ddec9855c49b8d753738'), 'name': 'Tawana Oberg', 'Exam': 79.24755285478162, 'Quiz': 97.28127199858804, 'HomeWork': 67.0528222080174, 'Total': 243.58164706138706, 'Percentage': 81.19388235379569}
{'_id': ObjectId('6231ddec9855c49b8d753739'), 'name': 'Malisa Jeanes', 'Exam': 40.68676040665008, 'Quiz': 52.60826688242043, 'HomeWork': 94.67979508129564, 'Total': 187.97482237036616, 'Percentage': 62.658274123455385}
{'_id': ObjectId('6231ddec9855c49b8d75373b'), 'name': 'Tresa Sinha', 'Exam': 52.22632020277269, 'Quiz': 65.68701091428014, 'HomeWork': 86.80410157346574, 'Total': 204.71743269051856, 'Percentage': 68.23914423017285}
{'_id': ObjectId('6231ddee9855c49b8d753740'), 'name': 'Dusti Lemmond', 'Exam': 91.51968055194875, 'Quiz': 50.37682668957234, 'HomeWork': 51.53939113583016, 'Total': 193.43589837735124, 'Percentage': 64.47863279245041}
{'_id': ObjectId('6231ddf09855c49b8d753748'), 'name': 'Jenise Mcguffie', 'Exam': 83.68438201130127, 'Quiz': 73.79931763764928, 'HomeWork': 89.57200947426745, 'Total': 247.055709123218, 'Percentage': 82.35190304107267}
{'_id': ObjectId('6231ddf09855c49b8d75374a'), 'name': 'Harriett Velarde', 'Exam': 41.47988283148075, 'Quiz': 95.69493673358075, 'HomeWork': 83.03916048182315, 'Total': 220.21398004688467, 'Percentage': 73.40466001562822}
{'_id': ObjectId('6231ddf19855c49b8d75374b'), 'name': 'Kam Senters', 'Exam': 49.8822537074033, 'Quiz': 45.29515361387067, 'HomeWork': 68.88048980292801, 'Total': 164.057897124202, 'Percentage': 54.68596570806733}
{'_id': ObjectId('6231ddf19855c49b8d75374e'), 'name': 'Leola Lundin', 'Exam': 60.314725741828, 'Quiz': 41.12327471818652, 'HomeWork': 74.8699176311771, 'Total': 176.30791809119162, 'Percentage': 58.76930603039721}
{'_id': ObjectId('6231ddf29855c49b8d753750'), 'name': 'Adrien Renda', 'Exam': 64.16109192679477, 'Quiz': 66.93730600935531, 'HomeWork': 96.0560340227047, 'Total': 227.1544319588548, 'Percentage': 75.71814398628493}
{'_id': ObjectId('6231ddf29855c49b8d753751'), 'name': 'Efrain Claw', 'Exam': 94.67153825229884, 'Quiz': 82.30087932110595, 'HomeWork': 75.86075840047938, 'Total': 252.83317597388418, 'Percentage': 84.27772532462807}
{'_id': ObjectId('6231ddf29855c49b8d753753'), 'name': 'Mariela Sherer', 'Exam': 47.67196715489599, 'Quiz': 41.55743490493954, 'HomeWork': 70.4612811769744, 'Total': 159.69068323680995, 'Percentage': 53.230227745603315}